version: '3.8'
services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      - PORT=8000 
      - DATABASE_URL=lol
    depends_on:
      - db
        # condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules  
    command: ["npm", "run", "dev"] 
    restart: always

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
